config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    if params[:flat_type].present?
      @query = params[:flat_type]
      @flats = Flat.where("name LIKE ?", "%#{params[:flat_type]}%")
      # Preventing SQL Injection and Database error for
      # unknown characters
    else
      @flats = Flat.all
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(set_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(set_params)
      redirect_to flat_path(@flat)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flat_path(@flat), status: :see_other
  end

  private

  def set_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/edit.html.erb
<h1>Edit the flat</h1>

<%= render "form" %>

app/views/flats/index.html.erb
<div class="row">
  <div class="container col-12 ms-5 mt-2">
    <h1>All our Flats (<%= @flats.length %>)</h1>
    <div class="col-sm-12 col-md-12">
      <ul class= "d-flex flex-wrap d-block">
        <% @flats.each do |flat| %>
          <li class="col-sm-12 col-md-4 border d-flex flex-column justify-content-between w-25 mx-3 mb-3  bg-secondary bg-opacity-25">
            <img src="https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200" alt="flat-image">
          <div class="d-flex flex-column mx-3 my-3 p-2">
            <h3><%= flat.name %></h3>
            <%= flat.address %>
            <div class="flex-row gap-1">
              <i class="fa-sharp fa-solid fa-users me-1"></i><%= flat.number_of_guests  %>
              <i class="fa-solid fa-euro-sign me-1 ms-2"></i><%= flat.price_per_night %>
            </div>
          </div>
            <div class="bg-white p-2 d-flex ">
              <%= link_to("More info", flat_path(flat), class: "text-decoration-none me-2") %>
              <%= link_to("Edit", edit_flat_path(flat), class: "text-decoration-none me-2 text-warning") %>
              <%= link_to("Delete", flat_path(flat),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-decoration-none text-danger") %>
            </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<%= render "form" %>

app/views/flats/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200);">
</div>

<div class="container d-flex" style="position: absolute; top:30%; left:10%;">
  <div class="flex-column col-8 me-3">
    <div class="bg-light p-3">
      <h2 class="fs-2 fw-bold"><%= @flat.name %></h2>
      <p class="fs-5"><%= @flat.address %></p>
    </div>
    <div class="bg-light p-3 mt-2">
      <h2 class="fs-2 fw-bold">A bit more about this flat...</h2>
      <p class="fs-5"><%= @flat.description %></p>
    </div>
    <div class="bg-light p-3 mt-2">
      <h2 class="fs-2 fw-bold">Details</h2>
      <i class="fa-sharp fa-solid fa-users me-1"></i><%= @flat.number_of_guests  %>
      <i class="fa-solid fa-euro-sign me-1 ms-2"></i><%= @flat.price_per_night %>
    </div>
  </div>
    <div class="bg-light col-3 p-3 mt-2">
      <p><strong>Book this place!</strong></p>
      <form action="#">
        <div class="d-flex flex-column">
          <div class="flex-row">
            <label for="from" class="w-25">From: </label>
            <input type="date" name="from" class="form-control">
          </div>
          <div class="flex-row">
          <label for="to">To: </label>
          <input type="date" name="to" class="form-control">
          </div>
          <button type="submit"class="btn btn-success mt-1">Book</button>
        </div>
      </form>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <%= link_to("Simple Airbnb", flats_path, class: "navbar-brand") %>
        <form class="d-flex justify-content-end"  method="GET" role="search">
          <input class="form-control me-2" name="flat_type" type="search" placeholder="Search" aria-label="Search" value="<%= params[:flat_type] %>">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <%= link_to("Add a flat", new_flat_path, class: "btn btn-outline-success") %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>